# 無効にするルール
disabled_rules:
- trailing_whitespace # 改行
- type_name # クラス名

# 一行の文字列制限を300文字に変更
line_length: 300

# クラスの行数
type_body_length:
- 200 # warning
- 400 # error

# 変数名の最大文字数
variable_name_max_length:
- 60 # warning
- 80 # error

# 変数名の最小文字数
variable_name_min_length:
- 1 # warning
- 0 # error

# 関数の長さ
function_body_length:
- 100 # warning
- 200 # error
